#!/usr/bin/env python3
"""Setup helper for workflows/whatsapp-webhook-security-gateway.json.

Computes the HMAC "commitment" value that goes into the gateway workflow's
"Evaluate GET Verification" Code node, WITHOUT ever putting your real verify
token on the command line, in a file, or in shell history.

Standard library only (secrets, hmac, hashlib, getpass) -- nothing to install.

Usage:
    python3 scripts/generate_webhook_verify_commitment.py            # generate a new token
    python3 scripts/generate_webhook_verify_commitment.py --existing # use a token you already have

This script NEVER accepts a token as a command-line argument (that would
leak it into shell history and process listings visible to other users on
the same machine) and NEVER writes anything to disk. The token, if
generated or entered, is only ever held in memory for this one run and
printed once to your terminal.

Read scripts/test_generate_webhook_verify_commitment.py to see this
behavior verified by automated tests.
"""

import argparse
import getpass
import hashlib
import hmac
import secrets
import sys

MIN_TOKEN_BYTES = 32  # 256 bits


def compute_commitment(token: str) -> str:
    """HMAC-SHA256(key=token, message=token), hex-encoded.

    This "commitment" is the exact, and only, value that is safe to paste
    into the workflow's EXPECTED_COMMITMENT constant. See
    workflows/whatsapp-webhook-security-gateway.md's "Security design"
    section for what this value can and cannot reveal about the token, and
    why a low-entropy token makes it guessable offline even though the
    commitment itself cannot be reversed directly.
    """
    key = token.encode("utf-8")
    return hmac.new(key, key, hashlib.sha256).hexdigest()


def generate_token() -> str:
    """Cryptographically random 256-bit (32-byte) hex token."""
    return secrets.token_hex(MIN_TOKEN_BYTES)


def read_existing_token() -> str:
    """Reads an existing token interactively -- never from argv, never from
    a file, and never echoed to the terminal."""
    token = getpass.getpass("Paste your existing verify token (input hidden): ").strip()
    if not token:
        raise SystemExit("No token entered. Aborting -- nothing was computed or printed.")
    return token


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a WhatsApp webhook verify token and its setup commitment, "
            "or compute the commitment for a token you already have. Never "
            "accepts the token itself as a command-line argument."
        )
    )
    parser.add_argument(
        "--existing",
        action="store_true",
        help="Prompt (hidden input) for a verify token you already have, instead of generating a new one.",
    )
    return parser


def main(argv):
    args = build_arg_parser().parse_args(argv)

    if args.existing:
        token = read_existing_token()
        if len(token.encode("utf-8")) < MIN_TOKEN_BYTES:
            print(
                f"WARNING: this token is shorter than the recommended {MIN_TOKEN_BYTES * 8}-bit "
                "(256-bit) minimum. A low-entropy token makes the published commitment "
                "guessable offline -- see the workflow documentation's Security design "
                "section. Consider generating a new one instead (run without --existing).",
                file=sys.stderr,
            )
        newly_generated = False
    else:
        token = generate_token()
        newly_generated = True

    commitment = compute_commitment(token)

    print()
    if newly_generated:
        print("Generated a new cryptographically random verify token (256 bits):")
        print()
        print(f"  {token}")
        print()
        print(
            "STORE THIS NOW in your n8n 'crypto' credential's Hmac Secret field AND in your "
            "password manager. It will not be shown again by this script and is not written "
            "to any file."
        )
    print()
    print("Commitment (paste this into the workflow's EXPECTED_COMMITMENT constant):")
    print()
    print(f"  {commitment}")
    print()
    print(
        "This commitment is derived from your token via a one-way HMAC and does not directly "
        "reveal it, but it IS a deterministic function of the token -- a low-entropy or "
        "guessable token can still be found by an attacker trying candidate tokens offline "
        "against this commitment. Only a token with genuine high entropy (256 bits, as "
        "generated by this script) makes that infeasible."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
